name: Docker Image CI

on: [push]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . -f Dockerfile -t docker.pkg.github.com/$GITHUB_REPOSITORY/a:$GITHUB_SHA -t ${{ secret.DOCKERHUB_USER }}/$GITHUB_REPOSITORY:$GITHUB_SHA
      
    - name: Login to GitHub registrty
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image to registrty
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/a:$GITHUB_SHA
      
    - name: Login to DockerHub
      run: docker login -u ${{ secret.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image to DockerHub
      run: docker push ${{ secret.DOCKERHUB_USER }}/$GITHUB_REPOSITORY
