name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login
      run: mkdir $HOME/.docker/ && echo regcred > $_/.config.json
    - name: Test login file exist
      run: cat $HOME/.docker/config.json
